// <auto-generated />
using System;
using FreshNFluffy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreshNFluffy.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116192313_CorrectedSeedProducts")]
    partial class CorrectedSeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreshNFluffy.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NutritionTypes")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Cakes",
                            NutritionTypes = 0
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Pastries",
                            NutritionTypes = 4
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Bread",
                            NutritionTypes = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Cookies",
                            NutritionTypes = 2
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Desserts",
                            NutritionTypes = 3
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Sweet Scones",
                            NutritionTypes = 12
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Salty Scones",
                            NutritionTypes = 17
                        });
                });

            modelBuilder.Entity("FreshNFluffy.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderRequestId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(9,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderRequestId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FreshNFluffy.Data.Models.OrderRequest", b =>
                {
                    b.Property<int>("OrderRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderRequestId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Notes")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderRequestId");

                    b.ToTable("OrderRequests");
                });

            modelBuilder.Entity("FreshNFluffy.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("NutritionTypes")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(9,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Rich chocolate sponge with fudge frosting.",
                            ImageUrl = "https://example.com/img/chocolate-fudge-cake.jpg",
                            Name = "Chocolate Fudge Cake",
                            NutritionTypes = 0,
                            Price = 29.90m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Moist carrot cake with walnuts and cinnamon.",
                            ImageUrl = "https://example.com/img/carrot-walnut-cake.jpg",
                            Name = "Carrot Walnut Cake",
                            NutritionTypes = 0,
                            Price = 27.50m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Plant-based chocolate cake, dairy-free.",
                            ImageUrl = "https://example.com/img/vegan-chocolate-cake.jpg",
                            Name = "Vegan Chocolate Cake",
                            NutritionTypes = 12,
                            Price = 30.90m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Classic French croissant, flaky and buttery.",
                            ImageUrl = "https://example.com/img/butter-croissant.jpg",
                            Name = "Butter Croissant",
                            NutritionTypes = 0,
                            Price = 3.20m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Croissant pastry filled with dark chocolate.",
                            ImageUrl = "https://example.com/img/pain-au-chocolat.jpg",
                            Name = "Pain au Chocolat",
                            NutritionTypes = 0,
                            Price = 3.80m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Crispy puff pastry with spiced apples, vegan.",
                            ImageUrl = "https://example.com/img/vegan-apple-turnover.jpg",
                            Name = "Vegan Apple Turnover",
                            NutritionTypes = 12,
                            Price = 4.10m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Naturally leavened sourdough bread.",
                            ImageUrl = "https://example.com/img/sourdough-loaf.jpg",
                            Name = "Sourdough Loaf",
                            NutritionTypes = 0,
                            Price = 6.50m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Hearty wholegrain loaf, great for sandwiches.",
                            ImageUrl = "https://example.com/img/wholegrain-bread.jpg",
                            Name = "Wholegrain Bread",
                            NutritionTypes = 0,
                            Price = 5.90m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Description = "Gluten-free loaf with mixed seeds.",
                            ImageUrl = "https://example.com/img/gluten-free-seed-bread.jpg",
                            Name = "Gluten-Free Seed Bread",
                            NutritionTypes = 13,
                            Price = 7.40m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            Description = "Soft cookies with dark chocolate chips.",
                            ImageUrl = "https://example.com/img/choc-chip-cookies.jpg",
                            Name = "Chocolate Chip Cookies",
                            NutritionTypes = 0,
                            Price = 6.90m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            Description = "Oat cookies with raisins and a hint of cinnamon.",
                            ImageUrl = "https://example.com/img/oat-raisin-cookies.jpg",
                            Name = "Oat & Raisin Cookies",
                            NutritionTypes = 0,
                            Price = 6.20m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4,
                            Description = "Crunchy almond cookies without added sugar.",
                            ImageUrl = "https://example.com/img/sugar-free-almond-cookies.jpg",
                            Name = "Sugar-Free Almond Cookies",
                            NutritionTypes = 19,
                            Price = 7.10m
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 5,
                            Description = "Creamy cheesecake with vanilla and biscuit base.",
                            ImageUrl = "https://example.com/img/classic-cheesecake.jpg",
                            Name = "Classic Cheesecake",
                            NutritionTypes = 0,
                            Price = 22.90m
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 5,
                            Description = "Low-carb cheesecake dessert cup.",
                            ImageUrl = "https://example.com/img/keto-cheesecake-cup.jpg",
                            Name = "Keto Cheesecake Cup",
                            NutritionTypes = 19,
                            Price = 8.90m
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 5,
                            Description = "Silky vegan mousse, dairy-free.",
                            ImageUrl = "https://example.com/img/vegan-chocolate-mousse.jpg",
                            Name = "Vegan Chocolate Mousse",
                            NutritionTypes = 12,
                            Price = 9.20m
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 6,
                            Description = "Soft vanilla scone, perfect with tea.",
                            ImageUrl = "https://example.com/img/vanilla-scone.jpg",
                            Name = "Vanilla Sweet Scone",
                            NutritionTypes = 0,
                            Price = 2.80m
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 6,
                            Description = "Buttery scone with blueberries.",
                            ImageUrl = "https://example.com/img/blueberry-scone.jpg",
                            Name = "Blueberry Sweet Scone",
                            NutritionTypes = 0,
                            Price = 3.10m
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 7,
                            Description = "Savory scone with cheddar cheese.",
                            ImageUrl = "https://example.com/img/cheddar-scone.jpg",
                            Name = "Cheddar Salty Scone",
                            NutritionTypes = 0,
                            Price = 3.40m
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 7,
                            Description = "Savory scone with olives and herbs.",
                            ImageUrl = "https://example.com/img/olive-herb-scone.jpg",
                            Name = "Olive & Herb Salty Scone",
                            NutritionTypes = 0,
                            Price = 3.60m
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 7,
                            Description = "Low-carb savory scone, keto friendly.",
                            ImageUrl = "https://example.com/img/keto-salty-scone.jpg",
                            Name = "Keto Salty Scone",
                            NutritionTypes = 17,
                            Price = 4.20m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FreshNFluffy.Data.Models.OrderItem", b =>
                {
                    b.HasOne("FreshNFluffy.Data.Models.OrderRequest", "OrderRequest")
                        .WithMany("Items")
                        .HasForeignKey("OrderRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FreshNFluffy.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderRequest");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FreshNFluffy.Data.Models.Product", b =>
                {
                    b.HasOne("FreshNFluffy.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreshNFluffy.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FreshNFluffy.Data.Models.OrderRequest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
